language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t aleksgor/u-complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run aleksgor/u-complex-test npm run test -- --coverage --watchAll=false

after_success:
  - docker build -t aleksgor/u-complex-client ./client
  - docker build -t aleksgor/u-complex-nginx ./nginx
  - docker build -t aleksgor/u-complex-server ./server
  - docker build -t aleksgor/u-complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aleksgor/u-complex-client
  - docker push aleksgor/u-complex-nginx
  - docker push aleksgor/u-complex-server
  - docker push aleksgor/u-complex-worker
  